// This file is part of Qtah.
//
// Copyright 2015 Bryan Gardiner <bog@khumba.net>
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU Affero General Public License version 3
// as published by the Free Software Foundation.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU Affero General Public License for more details.
//
// You should have received a copy of the GNU Affero General Public License
// along with this program.  If not, see <http://www.gnu.org/licenses/>.

// This is a small tool for normalizing signatures generated by Qt's SIGNAL()
// and SLOT() macros.

#include <iostream>
#include <QByteArray>
#include <QMetaObject>
#include <QString>

int main(int argc, char** argv) {
    if (argc < 2) {
        std::cerr << "Usage: ./normalize <separated Qt signal signatures to normalize> ...\n";
        return 0;
    }

    for (int i = 1; i < argc; ++i) {
        std::cout << QString(QMetaObject::normalizedSignature(argv[i])).toStdString() << std::endl;
    }

    return 0;
}
