#!/usr/bin/env bash

# This file is part of Qtah.
#
# Copyright 2015-2018 The Qtah Authors.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Lesser General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

# Generates source distribution tarballs (via "cabal sdist") for each of Qtah's
# packages.  cabal sdist doesn't like exposed-modules and other-modules not
# existing[1], so we create some empty files.  They'll be regenerated at
# configure time.
#
# [1] https://github.com/haskell/cabal/issues/719

set -euo pipefail
if [[ $(uname) = Darwin ]] && which greadlink >/dev/null 2>&1; then
    readlink() { greadlink "$@"; }
fi
projectDir=$(readlink -f "$0")
projectDir=$(dirname "$projectDir")
projectDir=$(dirname "$projectDir")
declare -r projectDir
. "$projectDir/common.sh"

msg "Cleaning existing build outputs."
cd "$projectDir"
./clean.sh

echo
msg "Building qtah-generator sdist."
goToPkg qtah-generator
run touch src/Graphics/UI/Qtah/Generator/Interface/Internal/Listener.hs
run cabal sdist

echo
msg "Building qtah-cpp sdist."
goToPkg qtah-cpp
run cabal sdist

echo
msg "Building qtah sdist."
goToPkg qtah
while read module; do
    file=src/$(tr . / <<<"$module").hs
    if ! [[ -e $file ]]; then
        if ! [[ -d $(dirname "$file") ]]; then
            run mkdir -p "$(dirname "$file")"
        fi
        run touch "$file"
    fi
done < <(cat qtah*.cabal | \
         awk '/^library/ {p=1; next}; /^[a-z]/ {p=0}; p && /Graphics\.UI\.Qtah/' | \
         tr -d ,)
run cabal sdist

echo
msg "Building qtah-examples sdist."
goToPkg qtah-examples
run cabal sdist
