# This file was auto-generated by cabal2nix. Please do NOT edit manually!

{ cabal, binary, cppop, qtah
, enableSplitObjs ? null
, forceParallelBuilding ? false
}:

cabal.mkDerivation (self: {
  pname = "qtah-examples";
  version = "0.1.0";
  src = ./.;
  isLibrary = false;
  isExecutable = true;
  buildDepends = [ binary cppop qtah ];
  extraLibraries = [ qtah ];

  preConfigure =
    if forceParallelBuilding
    then "configureFlags+=\" --ghc-option=-j$NIX_BUILD_CORES\""
    else null;

  meta = {
    homepage = "http://khumba.net/projects/qtah";
    description = "Example programs for Qtah Qt bindings";
    license = self.stdenv.lib.licenses.agpl3;
    platforms = self.ghc.meta.platforms;
  };
} // (if enableSplitObjs != null then { inherit enableSplitObjs; } else {}))
